### ISSUE TITLE
403 on direct debits request

### ISSUE THREAD

**Issue by dana-doherty** [MoneyMeg/starling-php-sdk#2]
Hello,

Im trying to get the direct debits of a customer simulated through the sandbox but im getting the following error Client error: `GET https://api.starlingbank.com/api/v1/direct-debit/mandates` resulted in a `403. Any guidance would be greatly appreciated.

**Comment by waxim** [comment]
Hey Sorry for the delay. Only just seen this. 403 is returned by starling if your token doesn't have the scope for the endpoint you're requesting.

Double your access token.

**Comment by dana-doherty** [comment]
Hi Alan, by double do you mean join access token with the customer ID?


Thanks,

Dana

________________________________
